name: Hello

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Cleanup previous root-owned site (one-time)
        run: |
          docker run --rm -v "$PWD":/ws alpine sh -c 'rm -rf /ws/DevOps/DevOps/site || true'

      - name: Run a one-line script
        run: echo Hello, world!
